#!/data/data/com.termux/files/usr/bin/sh
set -e

PREFIX="/data/data/com.termux/files/usr"
HOME="/data/data/com.termux/files/home"
DATA_DIR="$HOME/.local/share/hotvideo-downloads"
CONF="$HOME/.config/hotvideo-downloader"
CONFIG_FILE="$CONF/config.json"
DEFAULT_DIR="$HOME/.hotvideo-downloader/video"

case "$1" in
    configure)
        # 1. CHecking
        if [ -f "$PREFIX/bin/hotvideo" ]; then
            chmod +x "$PREFIX/bin/hotvideo"
        fi

        # 2. checking again
        mkdir -p "$DATA_DIR" "$CONF" "$DEFAULT_DIR"

        if [ ! -f "$CONFIG_FILE" ]; then
            cat << EOF > "$CONFIG_FILE"
{
  "dest_dir": "$DEFAULT_DIR"
}
EOF
        fi
    ;;

    upgrade|abort-upgrade|abort-remove|abort-deconfigure|triggered)
    ;;

    "")
        "$0" configure
    ;;

    *)
        echo "postinst was called with unknown arguments : \`$1'" >&2
        exit 1
    ;;
esac

exit 0
